### ISSUE TITLE
Email reply to address needs to be same as from address

### ISSUE THREAD

**Issue by tmassman** [propertyshelf/plone.mls.listing#8]
Or: reply-to can be removed, and from address needs to be the "sender".

This is so for agent contact portlet and maybe other places.

**Comment by zcashero** [comment]
Yes, so it seems that the "sender" would have to be the person who filled out the form (i.e. interestedbuyer@gmail.com).

Do you know if this would raise any spam flags by having a "sender" email (such as @gmail.com) that would differ from the SMTP server? I don't have any insight into this

**Comment by tmassman** [comment]
It is ok to have a 3rd party sender, but not ok (anymore) to have a sender different from a reply-to (domain). That is now causing the spam errors.

**Comment by tmassman** [comment]
Fixed with f25dc8e.
